### ISSUE TITLE
Integración de dataset latinoamérica

### ISSUE THREAD

**Issue by ZurMaD** [dbarcene/COVID-19-Panama#1]
Hola, junto con una organización sin fines de lucro se está tratando de centralizar la información de contagiados/muertos/recuperados covid-19 y estamos buscando un encargado por país. En tu caso Panamá.

El formato del csv se está manejando acorde al formato global https://github.com/CSSEGISandData/COVID-19 para luego poder juntar la data.
Esto comprende las siguientes columnas:
![image](https://user-images.githubusercontent.com/28235457/77204354-90926600-6ac0-11ea-9191-a30df328d09a.png)

Lo que necesitaria es subir los números por día de estos lugares:
![image](https://user-images.githubusercontent.com/28235457/77204381-9c7e2800-6ac0-11ea-833c-96d825464ece.png)

Podrías comentarme si estás interesado en aportar porfavor.
El dataset centralizado se propone en este repositorio: https://github.com/DataScienceResearchPeru/covid-19_pe

**Comment by dbarcene** [comment]
Hola, por el momento solo estaba haciendo un seguimiento personal de la información pública. Actualmente el gobierno Panameño ya consolidó los datos oficiales en la siguiente web: https://geosocial.maps.arcgis.com/apps/opsdashboard/index.html#/2c6e932c690d467b85375af52b614472

**Comment by ZurMaD** [comment]
Gracias por la información @dbarcene !
